//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by app.rc
//
#define IDD_ABOUT                       101
#define IDD_LOGIN                       102
#define IDD_TASK                        103
#define IDD_INFO                        104
#define IDD_JOB                         105
#define IDD_USER                        106
#define IDD_USERS                       107
#define IDD_PASS                        108
#define IDD_OPTIONS                     109
#define IDD_TERM                        110
#define IDB_TOOLBAR                     121
#define IDB_STATE                       122
#define IDR_MAINFRAME                   128
#define IDS_COL_STATE                   200
#define IDS_COL_CODE                    201
#define IDS_COL_JOB                     202
#define IDS_COL_REFER_DATE              203
#define IDS_COL_COMPANY                 204
#define IDS_COL_TASK                    205
#define IDS_COL_EDITION                 206
#define IDS_COL_SIZE                    207
#define IDS_COL_PAPER_FMT               208
#define IDS_COL_PAPER_NUM               209
#define IDS_COL_PRINT_FMT               210
#define IDS_COL_COLOR                   211
#define IDS_COL_PLAST_NUM               212
#define IDS_COL_NOTE                    213
#define IDS_COL_LOGIN                   301
#define IDS_COL_FULLNAME                302
#define IDS_COL_ROLE                    303
#define IDS_COL_WORK                    304
#define IDS_INF_PASS_CHANGE_FAILED      401
#define IDS_INF_PASS_CHANGE_SUCCESS     402
#define IDS_WRN_LOGIN_FAILED            501
#define IDS_QST_DELETE_USER             601
#define IDS_QST_DELETE                  602
#define IDS_QST_START                   603
#define IDS_QST_STOP                    604
#define IDS_QST_HISTORY                 605
#define IDS_QST_SUBMIT                  606
#define IDS_QST_JOB_DATA_NOT_ENOUGH     607
#define IDS_TAB_JOB                     701
#define IDS_TAB_ADD                     702
#define IDS_PROCESS_BAR_TITLE           703
#define IDS_TIT_INFO                    801
#define IDS_TIT_WARN                    802
#define IDS_TIT_CONF                    803
#define IDS_COL_SHOP                    901
#define IDS_COL_VALUE                   902
#define IDC_EB_LOGIN                    1001
#define IDC_EB_CODE                     1002
#define IDC_EB_EDITION                  1003
#define IDS_EMPTY_TEXT_PROCESS          1003
#define IDC_EB_NOTE                     1004
#define IDS_EMPTY_TEXT_WORK             1004
#define IDC_EB_SIZE                     1005
#define IDC_EB_PAPER_FMT                1006
#define IDC_EB_PAPER_NUM                1007
#define IDC_EB_PRINT_FMT                1008
#define IDC_EB_COLOR                    1009
#define IDC_EB_PALST_NUM                1010
#define IDC_EB_CONTACT                  1010
#define IDC_EB_FNAME                    1011
#define IDC_EB_MNAME                    1012
#define IDC_EB_LNAME                    1013
#define IDC_EB_PASS_OLD                 1014
#define IDC_EB_SERVER                   1015
#define IDC_EB_RELOAD_SPACE             1016
#define IDC_EB_PASS                     1017
#define IDC_EB_PASS_RE                  1018
#define IDC_LC_USERS                    1019
#define IDC_TAB_JOBS                    1021
#define IDC_DT_REFER_DATE               1022
#define IDC_LB_VALUES                   1023
#define IDC_CH_AUTO_RELOAD              1024
#define IDC_CB_COMPANY                  1025
#define IDC_CB_TASK                     1026
#define IDC_CB_ROLE                     1027
#define IDC_CB_WORK                     1030
#define IDC_BTN_DUP_JOB                 1031
#define IDC_BTN_DEL_JOB                 1032
#define IDC_BTN_UP                      1033
#define IDC_BTN_DOWN                    1034
#define IDC_BTN_HISTORY                 1035
#define IDC_BTN_EDIT                    1036
#define IDC_BTN_ADD                     1038
#define IDC_BTN_DEL                     1039
#define IDC_DB_PROCESS                  1040
#define IDC_LC_PROCESS                  1041
#define IDC_LB_WORK                     1042
#define IDC_LB_VALUE                    1043
#define IDC_CB_QUEUE                    1101
#define IDC_CB_COL_CODE                 1301
#define IDC_CB_COL_JOB_FROM             1302
#define IDC_EB_COL_JOB_FROM             1303
#define IDC_CB_COL_JOB_TO               1304
#define IDC_EB_COL_JOB_TO               1305
#define IDC_CB_COL_REFER_DATE_FROM      1306
#define IDC_DT_COL_REFER_DATE_FORM      1307
#define IDC_CB_COL_REFER_DATE_TO        1308
#define IDC_CH_COL_CODE                 1309
#define IDC_DT_COL_REFER_DATE_TO        1310
#define IDC_EB_COL_CODE                 1311
#define IDC_CB_COL_COMPANY              1312
#define IDC_EB_COL_COMPANY              1313
#define IDC_CB_COL_TASK                 1314
#define IDC_EB_COL_TASK                 1315
#define IDC_CB_COL_EDITION_FROM         1316
#define IDC_EB_COL_EDITION_FROM         1317
#define IDC_CB_COL_EDITION_TO           1318
#define IDC_EB_COL_EDITION_TO           1319
#define IDC_CB_COL_SIZE                 1320
#define IDC_EB_COL_SIZE                 1321
#define IDC_CB_COL_PAPER_FMT            1322
#define IDC_EB_COL_PAPER_FMT            1323
#define IDC_CB_COL_PRINT_FMT            1324
#define IDC_EB_COL_PRINT_FMT            1325
#define IDC_CB_COL_COLOR                1326
#define IDC_EB_COL_COLOR                1327
#define IDC_CB_COL_NOTE                 1328
#define IDC_EB_COL_NOTE                 1329
#define IDC_CB_COL_PAPER_NUM_FROM       1330
#define IDC_EB_COL_PAPER_NUM_FROM       1331
#define IDC_CB_COL_PAPER_NUM_TO         1332
#define IDC_EB_COL_PAPER_NUM_TO         1333
#define IDC_CB_COL_PLAST_NUM_FROM       1334
#define IDC_CB_COL_CODE_O               1335
#define IDC_CB_COL_JOB_O                1336
#define IDC_CB_COL_REFER_DATE_O         1337
#define IDC_CB_COL_COMPANY_O            1338
#define IDC_CB_COL_TASK_O               1339
#define IDC_CB_COL_EDITION_O            1340
#define IDC_CB_COL_SIZE_O               1341
#define IDC_CB_COL_PAPER_FMT_O          1342
#define IDC_CB_COL_PAPER_NUM_O          1343
#define IDC_CB_COL_PRINT_FMT_O          1344
#define IDC_CB_COL_COLOR_O              1345
#define IDC_CB_COL_NOTE_O               1346
#define IDC_EB_COL_PLAST_NUM_FROM       1347
#define IDC_CB_COL_PLAST_NUM_TO         1348
#define IDC_EB_COL_PLAST_NUM_TO         1349
#define IDC_CB_COL_PLAST_NUM_O          1350
#define IDC_CH_COL_JOB                  1359
#define IDC_CH_COL_REFER_DATE           1360
#define IDC_CH_COL_COMPANY              1361
#define IDC_CH_COL_TASK                 1362
#define IDC_CH_COL_EDITION              1363
#define IDC_CH_COL_SIZE                 1364
#define IDC_CH_COL_PAPER_FMT            1365
#define IDC_CH_COL_PAPER_NUM            1366
#define IDC_CH_COL_PRINT_FMT            1367
#define IDC_CH_COL_COLOR                1368
#define IDC_CH_COL_NOTE                 1369
#define IDC_CH_COL_PLAST_NUM            1370
#define ID_FILE_ADD                     32771
#define ID_FILE_EDIT                    32772
#define ID_FILE_DELETE                  32773
#define ID_FILE_START                   32774
#define ID_FILE_STOP                    32775
#define ID_FILE_HISTORY                 32776
#define ID_FILE_SUBMIT                  32777
#define ID_FILE_INFO                    32778
#define ID_VIEW_PROCESS_BAR             32781
#define ID_VIEW_RELOAD                  32782
#define ID_VIEW_QUEUE                   32783
#define ID_VIEW_HISTORY                 32784
#define ID_VIEW_TERM                    32785
#define ID_PRIOR_TOP                    32791
#define ID_PRIOR_UP                     32792
#define ID_PRIOR_DOWN                   32793
#define ID_PRIOR_BOTTOM                 32794
#define ID_TOOLS_LOGIN                  32801
#define ID_TOOLS_USERS                  32803
#define ID_TOOLS_PASS                   32804
#define ID_TOOLS_OPTIONS                32805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         34001
#define _APS_NEXT_CONTROL_VALUE         1401
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
